# Set the version of docker compose to use
version: "3.9"

networks:
  dev-lxp_network:
    external: true

volumes:
  dev-pg:
    driver: local
  dev-mongo:
    driver: local
  dev-api:
    driver: local
  dev-logs:
    driver: local

# The containers that compose the project
services:
  dev-db-pg:
    image: postgres:latest
    restart: always
    container_name: dev-lxp-prisma
    volumes:
      - dev-pg:/var/lib/postgresql/data
    networks:
      - dev-lxp_network
    ports:
      - "5600:5533"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_POSTGRES_DB}
  dev-db-mongo:
    image: mongo:latest
    restart: always
    container_name: dev-lxp-mongo
    volumes:
      - dev-mongo:/data/db
    networks:
      - dev-lxp_network
    ports:
      - "28000:28017"
  dev-api:
    image: studiostep/lxp:latest
    pull_policy: always
    # build: .
    volumes:
      - dev-api:/app/api/dist/uploads
      - dev-logs:/app/api/dist/logs
    networks:
      - dev-lxp_network
    restart: always
    container_name: dev-lxp-api
    ports:
      - "5002:5002"
    links:
      - dev-db-pg
      - dev-db-mongo
    depends_on:
      - dev-db-pg
      - dev-db-mongo
    environment:
      - DATABASE_URL=${DEV_DATABASE_URL}
      - MONGO_LOCAL_URL=${DEV_MONGO_LOCAL_URL}
      - SECRET=${SECRET}
