FROM nginx:alpine

# Copier TinyMCE depuis node_modules (à exécuter depuis ton projet)
COPY ./front/node_modules/tinymce /usr/share/nginx/html/tinymce
COPY ./front/src/assets/fr_FR/ /usr/share/nginx/html/tinymce/langs/fr_FR

# Copie de la configuration Nginx personnalisée si nécessaire
COPY ./nginx.conf /etc/nginx/nginx.conf

# Exposer le port 80 pour servir les fichiers
EXPOSE 3200

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]