networks:
  lxp_network:
    external: true

volumes:
  pg:
    driver: local
  mongo:
    driver: local
  api:
    driver: local
  logs:
    driver: local

# The containers that compose the project
services:
  db-pg:
    image: postgres:latest
    restart: always
    container_name: lxp-prisma
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - lxp_network
    ports:
      - "5500:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  db-mongo:
    image: mongo:latest
    restart: always
    container_name: lxp-mongo
    volumes:
      - mongo:/data/db
      - ./api/mongodb/init-db:/docker-entrypoint-initdb.d
    networks:
      - lxp_network
    ports:
      - "27000:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
  api:
    image: studiostep/lxp:latest
    pull_policy: always
    volumes:
      - api:/app/api/dist/uploads
      - api:/app/api/dist/src/uploads
      - logs:/app/api/dist/logs
    networks:
      - lxp_network
    restart: always
    container_name: lxp-api
    ports:
      - "5001:5001"
    links:
      - db-pg
      - db-mongo
    depends_on:
      - db-pg
      - db-mongo
    environment:
      - DATABASE_URL=${DEV_DATABASE_URL}
      - MONGO_LOCAL_URL=${DEV_MONGO_LOCAL_URL}
      - FIXTURES_MONGO_URL=${FIXTURES_MONGO_URL}
      - SECRET=${SECRET}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - SMTP=${SMTP}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PORT=${SMTP_PORT}
      - FROM=${FROM}
      - REGISTER_SECRET=${REGISTER_SECRET}
      - FRONT_URL=${FRONT_URL}
