export const themes = {
  light: "classic",
  dark: "classic-dark",
};

export const lightThemes = [
  "classic",
  "ocean",
  "linen",
  "sage",
  "lavender",
  "sunrise",
  "glacier",
  "sand",
  "pearl",
  "mint",
  "blossom",
  "sky",
  "lemon",
  "clay",
  "ice",
  "paper",
] as const;

export const darkThemes = [
  "classic-dark",
  "aurora",
  "ember",
  "abyss",
  "graphite",
  "plum",
  "moss",
  "cobalt",
  "midnight",
  "forest-night",
  "coffee",
  "amethyst",
  "storm",
  "wine",
  "teal-night",
  "obsidian",
] as const;

export const defaultEnabledThemes = [
  "classic",
  "ocean",
  "linen",
  "sage",
  "classic-dark",
  "aurora",
  "ember",
  "abyss",
] as const;

export const themeLabels: Record<string, string> = {
  classic: "Classique",
  ocean: "Océan",
  linen: "Lin",
  sage: "Forêt",
  lavender: "Lavande",
  sunrise: "Lever du jour",
  glacier: "Glacier",
  sand: "Sable",
  "classic-dark": "Classique sombre",
  aurora: "Aurore",
  ember: "Braise",
  abyss: "Abysses",
  graphite: "Graphite",
  plum: "Prune",
  moss: "Mousse",
  cobalt: "Cobalt",
  pearl: "Perle",
  mint: "Menthe",
  blossom: "Floraison",
  sky: "Ciel",
  lemon: "Citron",
  clay: "Argile",
  ice: "Glace",
  paper: "Papier",
  midnight: "Minuit",
  "forest-night": "Forêt nocturne",
  coffee: "Café",
  amethyst: "Améthyste",
  storm: "Orage",
  wine: "Bordeaux",
  "teal-night": "Sarcelle nocturne",
  obsidian: "Obsidienne",
};
