export const permDefsInterface = {
  "interface:admin": {
    layout: ["admin", "teacher", "student"],
    component: [
      "hobbie",
      "social-network",
      "course",
      "group",
      "parcours",
      "profile",
      "user",
      "role",
      "course",
      "profile",
      "lesson",
      "module",
      "formation",
    ],
  },
  "interface:teacher": {
    layout: ["teacher", "student"],
    component: ["calendar"],
  },
  "interface:student": { layout: ["student"], component: ["calendar"] },
};

export const permDefsActions = {
  admin: {
    read: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "admin",
      "teacher",
      "student",
      "everything",
    ],
    write: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "admin",
      "teacher",
      "student",
      "everything",
    ],
    update: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "objective",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "admin",
      "teacher",
      "student",
      "everything",
    ],
    delete: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "formation",
      "parcours",
      "objective",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "admin",
      "teacher",
      "student",
      "everything",
    ],
  },
  teacher: {
    read: [
      "role",
      "tag",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "teacher",
      "student",
      "everything",
    ],
    write: [
      "role",
      "tag",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "teacher",
      "student",
      "everything",
    ],
    update: [
      "role",
      "tag",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "teacher",
      "student",
      "everything",
    ],
    delete: [
      "role",
      "tag",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "teacher",
      "student",
      "everything",
    ],
  },
  student: {
    read: [
      "tag",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
    ],
    write: ["cursus"],
    update: ["cursus"],
    delete: ["cursus"],
  },
};
