const permDefs = {
  admin: {
    read: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "admin",
      "miniAdmin",
      "teacher",
      "bossTeacher",
      "student",
      "coach",
      "stagiaire",
    ],
    write: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "admin",
      "miniAdmin",
      "teacher",
      "bossTeacher",
      "student",
      "coach",
      "stagiaire",
    ],
    update: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "admin",
      "miniAdmin",
      "teacher",
      "bossTeacher",
      "student",
      "coach",
      "stagiaire",
    ],
    delete: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "admin",
      "miniAdmin",
      "teacher",
      "bossTeacher",
      "student",
      "coach",
      "stagiaire",
    ],
  },
  miniAdmin: {
    read: [],
    write: [],
    update: [],
    delete: [],
  },
  teacher: {
    read: [],
    write: [],
    update: [],
    delete: [],
  },
  student: {
    read: [],
    write: [],
    update: [],
    delete: [],
  },
  bossTeacher: {
    read: [],
    write: [],
    update: [],
    delete: [],
  },
  stagiaire: {
    read: [],
    write: [],
    update: [],
    delete: [],
  },
  coach: {
    read: [],
    write: [],
    update: [],
    delete: [],
  },
};

export default permDefs;
