ALTER TABLE "Activity" ADD COLUMN "duplicationIndex" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "duplicationIndex" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Lesson" ADD COLUMN "duplicationIndex" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Module" ADD COLUMN "duplicationIndex" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Parcours" ADD COLUMN "duplicationIndex" INTEGER NOT NULL DEFAULT 0;

