export const permDefsInterface = {
  "interface:admin": {
    layout: ["admin", "teacher", "student"],
    component: ["calendar"],
  },
  "interface:teacher": {
    layout: ["teacher", "student"],
    component: ["calendar", "lessons-rating-stats", "last-feedback"],
  },
  "interface:student": {
    layout: ["student"],
    component: ["calendar", "start-lesson-button", "progression"],
  },
};

export const permDefsActions = {
  admin: {
    read: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "admin",
      "teacher",
      "student",
      "everything",
    ],
    write: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "admin",
      "teacher",
      "student",
      "everything",
    ],
    update: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "objective",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "admin",
      "teacher",
      "student",
      "everything",
    ],
    delete: [
      "role",
      "tag",
      "permission",
      "user",
      "group",
      "formation",
      "parcours",
      "objective",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "admin",
      "teacher",
      "student",
      "everything",
    ],
  },
  teacher: {
    read: [
      "tag",
      "objective",
      "role",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "teacher",
      "student",
      "everything",
    ],
    write: [
      "tag",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "teacher",
      "student",
      "everything",
    ],
    update: [
      "tag",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "teacher",
      "student",
      "everything",
    ],
    delete: [
      "tag",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
      "teacher",
      "student",
      "everything",
    ],
  },
  student: {
    read: [
      "tag",
      "user",
      "group",
      "formation",
      "parcours",
      "module",
      "course",
      "bonusSkill",
      "lesson",
      "cursus",
    ],
    write: ["cursus", "tag"],
    update: ["cursus", "tag"],
    delete: ["cursus", "tag"],
  },
};
