import {
  Selection,
  Table,
  TableCell,
  TableHeader,
  TableRow,
  Heading,
  Document,
  TrailingNode,
  FontSize,
  Link,
  ImageBlock,
  Columns,
  Column,
  TaskList,
  TaskItem,
  StarterKit,
  TextStyle,
  FontFamily,
  Color,
  Highlight,
  Underline,
  CharacterCount,
  TextAlign,
  Subscript,
  Superscript,
  Typography,
  Placeholder,
  Focus,
  Dropcursor,
} from ".";

export const ExtensionKit = () => [
  Document,
  Columns,
  TaskList,
  TaskItem.configure({
    nested: true,
  }),
  Column,
  Selection,
  Heading.configure({
    levels: [1, 2, 3],
  }),
  StarterKit.configure({
    document: false,
    dropcursor: false,
    heading: false,
    horizontalRule: false,
  }),
  TextStyle,
  FontSize,
  FontFamily,
  Color,
  TrailingNode,
  Link.configure({
    openOnClick: false,
  }),
  Highlight.configure({ multicolor: true }),
  Underline,
  CharacterCount.configure({ limit: 50000 }),
  ImageBlock,
  TextAlign.configure({
    types: ["heading", "paragraph"],
  }),
  Subscript,
  Superscript,
  Table,
  TableCell,
  TableHeader,
  TableRow,
  Typography,
  Placeholder.configure({
    placeholder: "Start writing...",
  }),
  Focus,
  Dropcursor,
];
