import { BookOpen, MousePointer2, GraduationCap, Lightbulb, Rocket, Sparkles } from "lucide-react";

export const platformQualities = [
  { label: "Accessible", icon: BookOpen, description: "Les ressources de formation réunies dans un même espace.", features: ["Des parcours organisés en modules et en leçons.", "Des contenus texte, vidéo et des ressources à consulter.", "Des thèmes clairs et sombres pour choisir son confort de lecture."], screenshot: "/images/auth-qualities/accessible.webp", screenshotAlt: "Liste des formations et parcours dans ANDRIA" },
  { label: "Novatrice", icon: Lightbulb, description: "L’intelligence artificielle au service de l’apprentissage.", features: ["Un assistant conversationnel pour accompagner les apprenants.", "Une aide par IA à la rédaction des contenus pédagogiques.", "Des analyses du profil et de la progression des apprenants."], screenshot: "/images/auth-qualities/novatrice.webp", screenshotAlt: "Interface de l’assistant ANDRIA avec un échange illustratif" },
  { label: "Dynamique", icon: Rocket, description: "Des formats variés pour apprendre et pratiquer.", features: ["Des activités mêlant textes, images et vidéos.", "Des quiz pour mettre ses connaissances à l’épreuve.", "Un suivi de progression au fil des modules."], screenshot: "/images/auth-qualities/dynamique.webp", screenshotAlt: "Page de contenu d’un module de formation" },
  { label: "Réactive", icon: Sparkles, description: "Des outils pour suivre et accompagner la formation.", features: ["Un assistant conversationnel accessible pendant l’apprentissage.", "Un calendrier pour retrouver les rendez-vous de formation.", "Des retours et des indicateurs pour suivre les apprenants."], screenshot: "/images/auth-qualities/reactive.webp", screenshotAlt: "Calendrier de suivi d’un parcours" },
  { label: "Intuitive", icon: MousePointer2, description: "Des repères pour se concentrer sur l’essentiel.", features: ["Une navigation structurée par parcours, modules et leçons.", "Un tableau de bord pour retrouver les informations de formation.", "Un calendrier centralisé pour consulter son planning."], screenshot: "/images/auth-qualities/intuitive.webp", screenshotAlt: "Tableau de bord ANDRIA et ses actions principales" },
  { label: "Adaptative", icon: GraduationCap, description: "Un profil d’apprentissage qui tient compte de chacun.", features: ["Un niveau de départ renseigné à l’arrivée sur la plateforme.", "Un rythme d’apprentissage au choix : progressif, standard ou soutenu.", "Des préférences déclarées : exemples, pas-à-pas, synthèses ou exercices."], screenshot: "/images/auth-qualities/adaptative.webp", screenshotAlt: "Choix du rythme dans le profil d’apprentissage" },
];
