import { BookOpen, MousePointer2, GraduationCap, Lightbulb, Rocket, Palette, Gauge, ListChecks, HeartHandshake, Sparkles, Users, Link2, Tags, Mail, Settings, PartyPopper } from "lucide-react";

export const platformQualities = [
  { label: "Accessible", icon: BookOpen, description: "Les ressources de formation réunies dans un même espace.", features: ["Des parcours organisés en modules et en leçons.", "Des contenus texte, vidéo et des ressources à consulter.", "Des niveaux pédagogiques de la formation jusqu’à l’activité."], screenshot: "/images/auth-qualities/accessible.webp", screenshotAlt: "Liste des formations et parcours dans ANDRIA" },
  { label: "Harmonieuse", icon: Palette, description: "Une plateforme aux couleurs de chacun.", features: ["Des thèmes pour personnaliser l’apparence de la plateforme.", "Des modes clair et sombre pour choisir son confort de lecture.", "Les mêmes repères quel que soit le thème choisi."], screenshot: "", screenshotAlt: "Choix d’un thème de couleurs sur le tableau de bord apprenant" },
  { label: "Novatrice", icon: Lightbulb, description: "Un assistant pour accompagner l’apprentissage.", features: ["Un assistant conversationnel pour accompagner les apprenants.", "Des réponses en lien avec le contenu consulté.", "Un accès direct depuis la leçon en cours."], screenshot: "/images/auth-qualities/novatrice.webp", screenshotAlt: "Interface de l’assistant ANDRIA avec un échange illustratif" },
  { label: "Maîtrisée", icon: Gauge, description: "Des indicateurs pour piloter les usages et les contenus.", features: ["Le suivi de la consommation de l’IA par promotion.", "Le classement des cours selon les retours des apprenants.", "L’import de contenus existants, comme les cours Moodle."], screenshot: "", screenshotAlt: "Tableau de bord d’administration de l’IA et des contenus" },
  { label: "Dynamique", icon: Rocket, description: "Des activités variées pour créer des contenus vivants.", features: ["Des activités mêlant textes, images et vidéos.", "Un éditeur pour composer et enrichir les contenus.", "Une aide par IA à la rédaction des contenus pédagogiques."], screenshot: "/images/auth-qualities/dynamique.webp", screenshotAlt: "Page de contenu d’un module de formation" },
  { label: "Stimulante", icon: ListChecks, description: "Des quiz pour s’entraîner et progresser.", features: ["Des quiz de diagnostic avant un module.", "Des quiz de cours pour vérifier les notions abordées.", "Un entraînement avec l’assistant conversationnel."], screenshot: "", screenshotAlt: "Quiz de cours avec question à choix et correction" },
  { label: "Réactive", icon: Sparkles, description: "Un calendrier et des ressources pour organiser la formation.", features: ["Un calendrier pour retrouver les rendez-vous de formation.", "Des remises et évaluations clairement datées.", "Une médiathèque de ressources à portée de main."], screenshot: "/images/auth-qualities/reactive.webp", screenshotAlt: "Calendrier de suivi d’un parcours" },
  { label: "Attentive", icon: HeartHandshake, description: "Un accompagnement attentif de chaque apprenant.", features: ["Un retour d’humeur simple pour les apprenants.", "Des alertes de risque de décrochage pour l’équipe pédagogique.", "Un suivi des accompagnements en cours."], screenshot: "", screenshotAlt: "Alertes de décrochage et suivi des apprenants" },
  { label: "Intuitive", icon: MousePointer2, description: "Un espace pour apprendre et accompagner.", features: ["Une navigation structurée par parcours, modules et leçons.", "Un tableau de bord adapté à chaque rôle.", "Un assistant accessible depuis chaque page."], screenshot: "/images/auth-qualities/intuitive.webp", screenshotAlt: "Tableau de bord ANDRIA et ses actions principales" },
  { label: "Adaptative", icon: GraduationCap, description: "Une progression propre à chaque apprenant.", features: ["Un niveau de départ renseigné à l’arrivée sur la plateforme.", "Un rythme d’apprentissage au choix : progressif, standard ou soutenu.", "Des préférences déclarées : exemples, pas-à-pas, synthèses ou exercices."], screenshot: "/images/auth-qualities/adaptative.webp", screenshotAlt: "Choix du rythme dans le profil d’apprentissage" },
  { label: "Collective", icon: Users, description: "Un parcours commun, des groupes d’apprenants bien identifiés.", features: ["Plusieurs groupes peuvent suivre un même parcours.", "Chaque promotion rassemble ses propres apprenants.", "Les membres du groupe retrouvent les contenus du parcours associé."], screenshot: "", screenshotAlt: "Groupes et apprenants rattachés à un parcours" },
  { label: "Coordonnée", icon: Link2, description: "Une équipe pédagogique reliée aux groupes de son parcours.", features: ["Les formateurs sont affectés depuis le parcours.", "Les groupes associés affichent leurs formateurs.", "L’équipe pédagogique accompagne les promotions du parcours."], screenshot: "", screenshotAlt: "Formateurs du parcours et groupes associés" },
  { label: "Organisée", icon: Tags, description: "Des tags pour relier les contenus autour de sujets communs.", features: ["Un même tag peut être associé à plusieurs contenus.", "Formations, parcours, cours et ressources partagent des repères.", "Les sujets transversaux restent visibles dans les contenus."], screenshot: "", screenshotAlt: "Tag Accessibilité associé à plusieurs contenus pédagogiques" },
  { label: "Connectée", icon: Mail, description: "Les informations importantes arrivent aussi par email.", features: ["Les formateurs choisissent la fréquence de leurs récapitulatifs.", "Les alertes concernent les groupes de leurs parcours.", "Les apprenants sont informés lorsqu’une formation devient disponible."], screenshot: "", screenshotAlt: "Récapitulatifs de groupes et email de disponibilité des contenus" },
  { label: "Personnalisable", icon: Settings, description: "Une instance à l’image de votre organisme de formation.", features: ["L’identité, le logo et le site internet de l’organisme.", "Les thèmes clairs et sombres accessibles aux utilisateurs.", "Six modèles pour les emails de l’instance."], screenshot: "", screenshotAlt: "Personnalisation de l’identité, des thèmes et des emails de l’instance" },
  { label: "Encourageante", icon: PartyPopper, description: "Les accomplissements reconnus et les progrès célébrés.", features: ["Les cours terminés enrichissent le journal de l’apprenant.", "L’équipe pédagogique peut féliciter un accomplissement.", "L’apprenant reçoit les félicitations avec des confettis."], screenshot: "", screenshotAlt: "Accomplissement de Camille, félicitations et journal de progression" },
];
