import { BookOpen, MousePointer2, GraduationCap, Lightbulb, Rocket, Sparkles, Users, Link2, Tags, Mail, Settings, PartyPopper } from "lucide-react";

export const platformQualities = [
  { label: "Accessible", icon: BookOpen, description: "Les ressources de formation réunies dans un même espace.", features: ["Des parcours organisés en modules et en leçons.", "Des contenus texte, vidéo et des ressources à consulter.", "Des thèmes clairs et sombres pour choisir son confort de lecture."], screenshot: "/images/auth-qualities/accessible.webp", screenshotAlt: "Liste des formations et parcours dans ANDRIA" },
  { label: "Novatrice", icon: Lightbulb, description: "L’intelligence artificielle au service de l’apprentissage.", features: ["Un assistant conversationnel pour accompagner les apprenants.", "Une aide par IA à la rédaction des contenus pédagogiques.", "Des analyses du profil et de la progression des apprenants."], screenshot: "/images/auth-qualities/novatrice.webp", screenshotAlt: "Interface de l’assistant ANDRIA avec un échange illustratif" },
  { label: "Dynamique", icon: Rocket, description: "Des formats variés pour apprendre et pratiquer.", features: ["Des activités mêlant textes, images et vidéos.", "Des quiz pour mettre ses connaissances à l’épreuve.", "Un suivi de progression au fil des modules."], screenshot: "/images/auth-qualities/dynamique.webp", screenshotAlt: "Page de contenu d’un module de formation" },
  { label: "Réactive", icon: Sparkles, description: "Des outils pour suivre et accompagner la formation.", features: ["Un assistant conversationnel accessible pendant l’apprentissage.", "Un calendrier pour retrouver les rendez-vous de formation.", "Des retours et des indicateurs pour suivre les apprenants."], screenshot: "/images/auth-qualities/reactive.webp", screenshotAlt: "Calendrier de suivi d’un parcours" },
  { label: "Intuitive", icon: MousePointer2, description: "Des repères pour se concentrer sur l’essentiel.", features: ["Une navigation structurée par parcours, modules et leçons.", "Un tableau de bord pour retrouver les informations de formation.", "Un calendrier centralisé pour consulter son planning."], screenshot: "/images/auth-qualities/intuitive.webp", screenshotAlt: "Tableau de bord ANDRIA et ses actions principales" },
  { label: "Adaptative", icon: GraduationCap, description: "Un profil d’apprentissage qui tient compte de chacun.", features: ["Un niveau de départ renseigné à l’arrivée sur la plateforme.", "Un rythme d’apprentissage au choix : progressif, standard ou soutenu.", "Des préférences déclarées : exemples, pas-à-pas, synthèses ou exercices."], screenshot: "/images/auth-qualities/adaptative.webp", screenshotAlt: "Choix du rythme dans le profil d’apprentissage" },
  { label: "Collective", icon: Users, description: "Un parcours commun, des groupes d’apprenants bien identifiés.", features: ["Plusieurs groupes peuvent suivre un même parcours.", "Chaque promotion rassemble ses propres apprenants.", "Les membres du groupe retrouvent les contenus du parcours associé."], screenshot: "", screenshotAlt: "Groupes et apprenants rattachés à un parcours" },
  { label: "Coordonnée", icon: Link2, description: "Une équipe pédagogique reliée aux groupes de son parcours.", features: ["Les formateurs sont affectés depuis le parcours.", "Les groupes associés affichent leurs formateurs.", "L’équipe pédagogique accompagne les promotions du parcours."], screenshot: "", screenshotAlt: "Formateurs du parcours et groupes associés" },
  { label: "Organisée", icon: Tags, description: "Des tags pour relier les contenus autour de sujets communs.", features: ["Un même tag peut être associé à plusieurs contenus.", "Formations, parcours, cours et ressources partagent des repères.", "Les sujets transversaux restent visibles dans les contenus."], screenshot: "", screenshotAlt: "Tag Accessibilité associé à plusieurs contenus pédagogiques" },
  { label: "Connectée", icon: Mail, description: "Les informations importantes arrivent aussi par email.", features: ["Les formateurs choisissent la fréquence de leurs récapitulatifs.", "Les alertes concernent les groupes de leurs parcours.", "Les apprenants sont informés lorsqu’une formation devient disponible."], screenshot: "", screenshotAlt: "Récapitulatifs de groupes et email de disponibilité des contenus" },
  { label: "Personnalisable", icon: Settings, description: "Une instance à l’image de votre organisme de formation.", features: ["L’identité, le logo et le site internet de l’organisme.", "Les thèmes clairs et sombres accessibles aux utilisateurs.", "Six modèles pour les emails de l’instance."], screenshot: "", screenshotAlt: "Personnalisation de l’identité, des thèmes et des emails de l’instance" },
  { label: "Encourageante", icon: PartyPopper, description: "Les accomplissements reconnus et les progrès célébrés.", features: ["Les cours terminés enrichissent le journal de l’apprenant.", "L’équipe pédagogique peut féliciter un accomplissement.", "L’apprenant reçoit les félicitations avec des confettis."], screenshot: "", screenshotAlt: "Accomplissement de Camille, félicitations et journal de progression" },
];
