# Set the version of docker compose to use
version: "3.9"

networks:
  lxp_api:
    external: true

volumes:
  pg:
  mongo:

# The containers that compose the project
services:
  db-pg:
    image: postgres:latest
    restart: always
    container_name: lxp-prisma
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - lxp_api
    ports:
      - "5500:5432"
    environment:
      POSTGRES_USER: lxp-studio
      POSTGRES_PASSWORD: gandalf
      POSTGRES_DB: lxp
  db-mongo:
    image: mongo:latest
    restart: always
    container_name: lxp-mongo
    volumes:
      - mongo:/data/db
    networks:
      - lxp_api
    ports:
      - "25000:27017"
  api:
    image: lxp-api
    networks:
      - lxp_api
    restart: always
    container_name: lxp-api
    ports:
      - "5002:5001"
    links:
      - db-pg
      - db-mongo
    depends_on:
      - db-pg
      - db-mongo
    command: npm run start:prod
    environment:
      - DATABASE_URL=postgresql://lxp-studio:gandalf@db-pg:5432/lxp
      - MONGO_LOCAL_URL=mongodb://db-mongo:27017/lxp
