# Set the version of docker compose to use
version: "3.9"

networks:
  lxp_network:
    external: true

volumes:
  pg:
    driver: local
  mongo:
    driver: local
  api:
    driver: local
  logs:
    driver: local

# The containers that compose the project
services:
  db-pg:
    image: postgres:latest
    restart: always
    container_name: lxp-prisma
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - lxp_network
    ports:
      - "5500:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  db-mongo:
    image: mongo:latest
    restart: always
    container_name: lxp-mongo
    volumes:
      - mongo:/data/db
    networks:
      - lxp_network
    ports:
      - "27000:27017"
  api:
    #image: lxp-api
    build: .
    volumes:
      - api:/app/api/dist/uploads
      - logs:/app/api/dist/logs
    networks:
      - lxp_network
    restart: always
    container_name: lxp-api
    ports:
      - "5001:5001"
    links:
      - db-pg
      - db-mongo
    depends_on:
      - db-pg
      - db-mongo
    command: npm run start:dev
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_LOCAL_URL=${MONGO_LOCAL_URL}
