# Set the version of docker compose to use
version: "3.9"
name: lxp-api

networks:
  lxp_network:
    external: true

volumes:
  pg:
    driver: local
  mongo:
    driver: local

# The containers that compose the project
services:
  db-pg:
    image: postgres:latest
    restart: always
    container_name: lxp-prisma
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - lxp_network
    ports:
      - "5500:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  db-mongo:
    image: mongo:latest
    restart: always
    container_name: lxp-mongo
    volumes:
      - mongo:/data/db
    networks:
      - lxp_network
    ports:
      - "27000:27017"
