// prisma.config.ts
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import "dotenv/config";
import path from "node:path";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // chemins explicites vers le schema & les migrations
  schema: path.join("prisma", "schema.prisma"),
  migrations: {
    path: path.join("prisma", "migrations"),
  },

  // 👇 datasource requise pour migrate deploy
  datasource: {
    url: env("DATABASE_URL"),
  },
});
